# Generated by Django 5.1 on 2024-08-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
