# Generated by Django 5.1 on 2024-08-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userpost_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
