# Generated by Django 5.1 on 2024-08-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
