# Generated by Django 5.0.8 on 2024-08-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usermessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMessage',
            new_name='AnonMessage',
        ),
    ]
