# Generated by Django 5.0.8 on 2024-08-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_usermessage_anonmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedImageMimeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLimits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('max_image_size', models.IntegerField()),
                ('max_user_images', models.IntegerField()),
                ('max_post_length', models.IntegerField()),
                ('allowed_image_mimes', models.ManyToManyField(related_name='allowed_image_mimes', to='api.allowedimagemimetype')),
            ],
            options={
                'verbose_name_plural': 'User Limits',
            },
        ),
    ]
