services:

  redis:
    container_name: redis
    image: redis:7.4-alpine
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - ${POSTGRES_DB_PORT}:5432

  django_build:
    container_name: django_build
    depends_on:
      - redis
      - postgres
    build:
      dockerfile: Dockerfile.staging
    image: django_app:latest
    env_file:
      - .env

  celery_worker:
    container_name: celery_worker_local_staging
    user: nobody
    depends_on:
      - redis
      - postgres
      - django_build
    image: django_app:latest
    env_file:
      - .env
    volumes:
      - ../portfolio_api:/app
    command: sh -c "celery -A portfolio_api worker --loglevel=info"      

  celery_beat:
    container_name: celery_beat_local_staging
    user: nobody
    depends_on:
      - redis
      - postgres
      - django_build      
    image: django_app:latest
    env_file:
      - .env    
    volumes:
      - ../portfolio_api:/app
    command: sh -c "celery -A portfolio_api beat --loglevel=info"

  django:
    container_name: django_local_staging
    depends_on:
      - redis
      - postgres
      - django_build      
    image: django_app:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ../portfolio_api:/app
    # command: sh -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py seed_defaults && gunicorn portfolio_api.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    command: sh -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py seed_defaults && gunicorn -k uvicorn.workers.UvicornWorker portfolio_api.asgi:application --bind 0.0.0.0:8000 --workers 3"
    # command: sh -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py seed_defaults && python manage.py runserver 0.0.0.0:8000"