# Generated by Django 5.1.1 on 2024-09-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedImageMimeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLimits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('max_image_size', models.IntegerField(default=0)),
                ('max_user_images', models.IntegerField(default=0)),
                ('max_post_length', models.IntegerField(default=0)),
                ('max_chat_messages', models.IntegerField(default=0)),
                ('allowed_image_mimes', models.ManyToManyField(related_name='allowed_image_mimes', to='core.allowedimagemimetype')),
            ],
            options={
                'verbose_name_plural': 'User Limits',
            },
        ),
    ]
