name: Build and Push to ECR (Staging)

on:
  push:
    branches:
      - staging

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4         

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN_STAGE }}
          aws-region: ${{ secrets.AWS_REGION_STAGE }}

      - name: Create and push env to S3
        run: |
          echo "${{ secrets.DJANGO_ENV }}" > djangoenv
          source djangoenv
          aws s3 cp djangoenv s3://$AWS_S3_ENV_BUCKET_STAGE/django-celery.env          

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION_STAGE }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION_STAGE }}.amazonaws.com

      - name: Build Docker image
        working-directory: ./portfolio_api
        run: docker build -t eaportfolio-django:latest .

      - name: Tag Docker image
        run: docker tag eaportfolio-django:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION_STAGE }}.amazonaws.com/${{ secrets.AWS_ECR_REPO_STAGE }}:latest

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION_STAGE }}.amazonaws.com/${{ secrets.AWS_ECR_REPO_STAGE }}:latest
        