name: Call ECS Migration Task (Dev)

on:
  workflow_run:
    workflows:
      - 'Build and Push to ECR (Dev)'
    types:
      - completed

permissions:
  id-token: write
  contents: read      

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN_DEV }}
          aws-region: ${{ secrets.AWS_REGION_DEV }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3
        
      - name: Load environment variables
        run: |
          echo "${{ secrets.ENCODED_DJANGO_ENV }}" | base64 --decode > djangoenv
          
      - name: Run ECS Migration Task
        run: |
          source djangoenv
          export AWS_REGION=$AWS_REGION_DEV
          export AWS_CLUSTER_NAME=$AWS_MIGRATE_CLUSTER_NAME_DEV
          export AWS_MIGRATE_TASK_DEF=$AWS_MIGRATE_TASK_DEF_DEV
          export AWS_MIGRATE_SUBNETS=$AWS_MIGRATE_SUBNETS_DEV
          export AWS_MIGRATE_SECURITY_GROUP=$AWS_MIGRATE_SECURITY_GROUP_DEV
          python migration_script/migrate.py