name: Push env to S3 (Dev)

on:
  workflow_call:
    secrets:
      aws_role:
        required: true
      aws_region:
        required: true
      env:
        required: true
      bucket:
        required: true
    inputs:
      targetname:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  push_env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_role }}
          aws-region: ${{ secrets.aws_region }}

      - name: Create and push env to S3
        run: |
          echo "${{ secrets.env }}" | base64 --decode > envfile
          source envfile
          aws s3 cp envfile s3://${{ secrets.bucket }}/${{ inputs.targetname }}